---
title: "My First Markdown"
author: "Iris Yocarini"
date: "11 May 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is my first markdown file.

Download sleep study data
```{r}
library(readr)
sleep <- read_csv("http://vincentarelbundock.github.io/Rdatasets/csv/lme4/sleepstudy.csv") #no spaces
head(sleep)
```

Plot the data by subject
```{r warning =FALSE}
library(ggplot2)
ggplot(sleep, aes(x=Days, y = Reaction)) + 
  geom_point()+
  geom_smooth()+
  scale_x_continuous(breaks=seq(0,8,by=2))+
  facet_wrap(~Subject)
```

```{r warning=FALSE}
library(dplyr)
sleep %>% #pipe operator read from left to right instead of nested
  group_by(Subject) %>%
  summarise(mean(Reaction))
```

Mean-center reaction times and plot on a single axis
```{r}
sleep %>%
  group_by(Subject) %>%
  mutate(mean_centered_reaction=Reaction - mean(Reaction)) %>%
  ggplot(aes(x=Days, y = mean_centered_reaction,
             colour=factor(Subject))) +
  geom_smooth(show.legend=FALSE, se =FALSE)+ #exclude grey se around mean
  scale_x_continuous(breaks=seq(0,8,by=2))
```

